kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-kubernetes-deployment
spec:
  # A deployment's specification really only 
  # has a few useful options
  # 1. How many copies of each pod do we want?
  replicas: 3
  # 2. How do want to update the pods?
  strategy: Recreate
  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: spring-kubernetes
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: spring-kubernetes
    spec:
      containers:
        - name: hellospringazure
          image: 261219/hellospringazure:latest